[project]
name = "earth-observation-image-processing"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "gdown>=6.4.0",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pillow>=12.3.0",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.9.1",
]
